### ISSUE TITLE
messages payload is empty

### ISSUE THREAD

**Issue by DSchau** [DSchau/gatsby-mail#1]
When querying for messages/emails, the payload field is empty, so I can't display subject, sender, etc.

Something with OneGraph? Here's the query:

```graphql
query {
  google {
    gmail {
      messages(maxResults: 50) {
        messages {
          id
          payload {
            body {
              data
            }
            from
            to
            subject
          }
        }
      }
    }
  }
}
```

in my testing the entire payload is null, so can't even infer `from`, `to`, etc. etc.

cc @jlengstorf

**Comment by DSchau** [comment]
The query is [in this file](https://github.com/DSchau/gatsby-mail/blob/master/src/pages/index.js#L22-L41)

**Comment by sgrove** [comment]
This should be the working query:

```
query {
  google {
    gmail {
      threads(maxResults: 50) {
        threads {
          expanded {
            messages {
              id
              payload {
                body {
                  data
                }
                from
                to
                subject
              }
            }
          }
        }
      }
    }
  }
}
```

The issue is that we mirror the Gmail API too much - if you notice, we want the "expanded" threads object that has the full payload, because that's 1. how their api works and 2. how they describe their api working in their discovery api.

It's an artifact of trying to avoid overfetching, really. But this is GraphQL and we can be incredibly precise with the fields we need, so we should eliminate it, and provide a more idiomatic API, and hide the underlying api. We're on top of it!

**Comment by DSchau** [comment]
@sgrove thanks so much for the great explanation! I really appreciate it! Fixing now :)
