### ISSUE TITLE
"Sign in with Google temporarily disabled for this app"

### ISSUE THREAD

**Issue by papascott** [DSchau/gatsby-mail#19]
![screenshot_719](https://user-images.githubusercontent.com/8681117/49239025-ff4a3c80-f401-11e8-95ef-fa169efa2cd0.png)

As installed, Google won't let you authenticate to gatsby-mail. Unlike in the webinar, there is no link to get around the scary warning.

My workaround was to sign up for my own OneGraph account, create an app, and use that App Id for GATSBY_OG_APP_ID in .env.development. In the OneGraph App dashboard I added http://localhost:8000 to CORS Origins, and then I was able to use run and use gatsby-mail locally.

**Comment by sgrove** [comment]
Yeah, the issue here is that Google is very protective of Gmail access, and they want to review any apps before they have a chance to cause too much public damage. The middle-ground they've found is that you can have N people sign into your app before it's shut down for anyone except for you (the author of the Google app).

The reason you can use the OneGraph app is that it's be reviewed as a developer tool, and doesn't ask for "write" (send, really) permissions, so the review is softer. We've seen some pretty intense requests for redesigns/more informative verbiage, and fewer permissions on some of the apps using Gmail.

If you end up publishing a real GatsbyMail for others to use, you'd want to create an OAuth client in Google, add the client id/secret in the OneGraph app dashboard, and they have your app reviewed well before launching publicly.

**Comment by DSchau** [comment]
Thanks for weighing in @sgrove!

Since this is more of less for demo purposes (see the "Don't use this for anything real" _in_ the live app, ha) I'm going to close this out!

If you're interested in using any of this for a real app @papascott definitely check out some of the advice above to move past some of these technical hurdles/challenges.

**Comment by dnafication** [comment]
Will this issue resove if the developer created a new account in onegraph and used his/her appId in .env file ('GATSBY_OG_APP_ID')?

**Comment by DSchau** [comment]
@dnafication sorry for the delay--but yes that should work!

**Comment by MyIsaak** [comment]
Just to make peoples lives a bit easier I updated the readme to avoid this issue. In my case, I needed to create a onegraph account since my Google account requires permission which can only be accepted by a self-created account.

**Comment by DSchau** [comment]
@MyIsaak think that should do the trick, for now at least.

Longer term--I need to get off my laurels and actually make this a real app with Google OAuth authentication as @sgrove mentioned earlier.

**Comment by erdahuja** [comment]
Even for onegraph account it gave the same message, "Sign in with google is disabled". I also tried t connect oneGraph account with google, same message.

**Comment by myisaak** [comment]
Look at https://developers.google.com/identity/protocols/oauth2/javascript-implicit-flow
