### ISSUE TITLE
sending emails gives a 403

### ISSUE THREAD

**Issue by DSchau** [DSchau/gatsby-mail#2]
When sending a sendMessage mutation, the GraphQL API exposed by OneGraph fails with

```json
{
  "error": {
    "errors": [
      {
        "domain": "global",
        "reason": "insufficientPermissions",
        "message": "Insufficient Permission"
      }
    ],
    "code": 403,
    "message": "Insufficient Permission"
  }
}
```

**Comment by DSchau** [comment]
@sgrove I investigated this more last night, and it doesn't seem like the GraphQL query (as authored below) will ever work. Appears I need to add a googleOauth token, which doesn't work that great.

## Not working mutation

```graphql
mutation {
  google(
    auths: {
      gmailOAuthToken: "hunter2"
    }
  ) {
    gmail {
      sendMessage(
        data: {
          body: "hello hello"
          subject: "hi"
          to: "dustinschau@gmail.com"
          from: "dustin@gatsbyjs.com"
        }
      ) {
        message {
          threadId
        }
      }
    }
  }
}
```

## Working mutation

```graphql
mutation {
  google(
    auths: {
      gmailOAuthToken: "hunter2"
    }
  ) {
    gmail {
      sendMessage(
        data: {
          body: "hello hello"
          subject: "hi"
          to: "dustinschau@gmail.com"
          from: "dustin@gatsbyjs.com"
        }
      ) {
        message {
          threadId
        }
      }
    }
  }
}
```

Guessing I'm missing something here, possibly with the OAuth Gmail application, I created? Not sure! Any help would be sincerely appreciated!

![screen shot 2018-10-18 at 10 41 24 am](https://user-images.githubusercontent.com/3924690/47166924-e149d200-d2c2-11e8-8392-9f15db425944.png)

**Comment by dwwoelfel** [comment]
@DSchau The default Gmail client that OneGraph uses doesn't have permissions to use sensitive scopes. You can work around this by using your own OAuth client for your app. To do that, go to the OneGraph dashboard and set `Custom OAuth Credentials` (https://www.onegraph.com/dashboard). 

Once you set your client_id and secret, the OAuth flow will start to use your OAuth client.

![image](https://user-images.githubusercontent.com/476818/47171200-ec016880-d2bc-11e8-9f3e-cb325e6bcb81.png)

You'll still run into a problem using the onegraph auth flow because you'll need to ask for write scopes and we don't have a way for you to set your own scopes, yet. 

Question for you: how would you prefer to set the scopes? Would you rather set them as part of the config for your app on the OneGraph dashboard, or would you rather pass them in as an option when you call `auth.login('gmail')`?

**Comment by DSchau** [comment]
@dwwoelfel I've done that! I did update the scope after, so maybe I'll remove and try again! One sec.

I would usually prefer to set it up at the dashboard level. I think that _clicks_ more with me, and it's similar to how I think most other services work.

**Comment by dwwoelfel** [comment]
> I would usually prefer to set it up at the dashboard level. I think that clicks more with me, and it's similar to how I think most other services work.

Great, let me try to bang that out real quick.

**Comment by DSchau** [comment]
@dwwoelfel awesome! So just so I'm clear, this won't work until the OneGraph dashboard is updated with a way to set scopes--e.g. send email--correct?

**Comment by dwwoelfel** [comment]
> So just so I'm clear, this won't work until the OneGraph dashboard is updated with a way to set scopes--e.g. send email--correct?

That's right.

**Comment by dwwoelfel** [comment]
@DSchau Just pushed it up! If you go to the dashboard, you can set scopes for your gmail app. You can use the `gmail.all` scope to get read and write access. Be sure to also add `userinfo.email` and `userinfo.profile`. 

You'll also need to add `https://serve.onegraph.com/oauth/gmail/receive` to your OAuth clients Authorized redirect URIs.

![image](https://user-images.githubusercontent.com/476818/47179701-95ebef80-d2d3-11e8-80e0-569db02113bb.png)

**Comment by DSchau** [comment]
Confirmed 🎉 Thank you so much!

I'll close this out when I validate UI side.
